version: '3.8'

services:
  battleford-jukebox:
    image: ghcr.io/boxingoctopus/battleford-jukebox:latest
    container_name: battleford-jukebox
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - PLAYLIST_ID=${PLAYLIST_ID}
    volumes:
      - ./.cache:/app/.cache  # For Spotify token persistence
    restart: unless-stopped 