version: '3.8'

services:
  battleford-jukebox:
    build: .
    container_name: battleford-jukebox
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - PLAYLIST_ID=${PLAYLIST_ID}
    volumes:
      - ./.cache:/app/.cache  # For Spotify token persistence
    restart: unless-stopped 